### ISSUE TITLE
Integração do pagamento

### ISSUE THREAD

**Issue by rafaeleyng** [hackinpoa/tanovinho#8]

**Comment by rafaeleyng** [comment]
Apanhei um pouco no PayPal (consegui pagar mas não encontrei o pagamento) e deixei de lado. Agora fiz um pagamento pelo PagSeguro, me pareceu mais simples e melhor documentado.

**Comment by marlonbernardes** [comment]
Estou continuando a tarefa de integracão com PagSeguro, vou atribuir este issue pra mim.
